###testing api call
### User
###Get user
GET http://localhost:8000/api/v1/users
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MzQzMDI2NzcsImV4cCI6MTczNDM4OTA3N30.khR3PUVv65D1afSjUKAZxZ_3pFImnZLTuP4EcH0njAQ
###Post new user
POST  http://localhost:8000/api/v1/users
Content-Type: application/json


{
    "name":"saurab adhikari",
    "email":"a@a.com",
    "password":"1234"
}

###Login user
POST  http://localhost:8000/api/v1/users/login
Content-Type: application/json


{
    "email":"a@a.com",
    "password":"1234"
}


###Post new transaction
POST  http://localhost:8000/api/v1/transactions
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MzQ0MTY5MTksImV4cCI6MTczNDUwMzMxOX0._xEP5MaxW09QY9RkhZbRblY5V8UyYMYMDOoDRCYr6N0

{
 "type":"income",
 "title":"sale",
 "amount":"55",
 "tDate":"2024-02-04"   
  }



### Get transactions

GET http://localhost:8000/api/v1/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MzQzMDk2MjIsImV4cCI6MTczNDM5NjAyMn0.P0WZ5ocDa37oIGfghlFjWa8L2iGSJslSLD2e-MptZ9w


### Delete transactions

DELETE  http://localhost:8000/api/v1/transactions
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MzQzMDk2MjIsImV4cCI6MTczNDM5NjAyMn0.P0WZ5ocDa37oIGfghlFjWa8L2iGSJslSLD2e-MptZ9w



{"tranid":"675fb91cba876a8c29bbbbf1"}