###testing api call
### User
###Get user
GET http://localhost:8000/api/v1/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImFAYS5jb20iLCJpYXQiOjE3MzQyNDcyOTcsImV4cCI6MTczNDMzMzY5N30.j8AfEC7m23ciY7mliiBCrF6T8hAxHsuIVttt-DLwWTE
###Post new user
POST  http://localhost:8000/api/v1/users
Content-Type: application/json


{
    "name":"saurab adhikari",
    "email":"a@a.com",
    "password":"1234"
}

###Login user
POST  http://localhost:8000/api/v1/users/login
Content-Type: application/json


{
    "email":"a@a.com",
    "password":"1234"
}


###Post new transaction
POST  http://localhost:8000/api/v1/transactions

Content-Type: application/json



{
    "userID": "63f1a9c2e82e4e09bcee1234", 
    "amount": 100.50,
    "date": "2024-12-01T10:30:00Z",
    "description": "Grocery shopping",
    "createdAt": "2024-12-01T10:31:00Z"
  }